### ISSUE TITLE
Zone Templates 

### ISSUE THREAD

**Issue by 5hack** [loewexy/pdnsmanager#77] opened 2018-06-17 15:12 UTC
Thanks for the great software.
It would be really helpful if there was a way to save templates for quick provisioning of the domain that contains default setting. Like NS, WWW and common TXT records. and manually setting serial numbers.

Thanks 👍

**Comment by loewexy** [comment] 2018-06-17 15:14
Duplicate of #24

**Closed by loewexy** 2018-06-17 15:14 UTC
