### ISSUE TITLE
Update SEARCH module to find a record through the domains page

### ISSUE THREAD

**Issue by otolizz** [loewexy/pdnsmanager#119] opened 2020-01-27 13:15 UTC
Hello,

On a large infrastructure, it would be great if we could find a record from the domains page.
Actually, SEARCH module is only getting its result from the page you are viewing.

If you search for "toto" in the domains page, you'll get domains that contains "toto" in their name (like toto.com or test-toto.com), but i'd like to get the records too (like toto.test.com).

Do you think you could upgrade pdns-manager to get this functionality ?

**Comment by loewexy** [comment] 2020-01-27 14:34
That seems to be a duplicate of #13

**Closed by loewexy** 2020-01-27 14:34 UTC
