### ISSUE TITLE
LDAP / AD Support

### ISSUE THREAD

**Issue by stedeux** [loewexy/pdnsmanager#139] opened 2021-02-26 15:12 UTC
Can the application support the integration of an LDAP or AD?

**Comment by loewexy** [comment] 2021-02-27 08:45
This is a duplicate of #17 . Since version 2.0 PDNS Manager has a plugin API to write authentication plugins for arbitrary technologies. But I have no experience in LDAP. If you want to provide a new plugin here I can help you getting started with that.

**Closed as completed by loewexy** 2021-02-27 08:45 UTC
