### ISSUE TITLE
Header already sent

### ISSUE THREAD

**Issue by psi-4ward** [loewexy/pdnsmanager#29] opened 2017-01-09 22:25 UTC
Hey,

You have an output block over the php init stuff: https://github.com/lamclennan/pdnsmanager/blob/master/index.php#L17
which leads to `Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/index.php:17) in /var/www/html/lib/headers.php on line 19`

Chears

**Comment by TheFatherMind** [comment] 2017-07-10 03:30
I am seeing this error as well through nginx.  It is making it unusable.  Any idea when this will be fixed?

**Comment by loewexy** [comment] 2017-07-10 14:04
I am not able to reproduce this issue. Also a warning should not render the software unusable.

**Comment by TheFatherMind** [comment] 2017-07-10 17:45
I would be more than happy to set you up with access to a dev site on my server so that you can tinker with it if you like.  It does work.  Although it is filling my logs and I am unable to assign domains to users so only administrators can use the software.  Not sure if that is connected.

FYI: So far your version has been the best GUI I have seen yet.  (:  Looking forward to getting it 100% usable.

**Comment by TheFatherMind** [comment] 2017-07-10 17:49
Nevermind about the users domain access.  I just worked that part out.

**Comment by mauricemeyer** [comment] 2017-07-20 13:58
I tried to reproduce this on a Ubuntu Xenial (with PHP `5.6.31-1~ubuntu16.04.1+deb.sury.org+1`), but I don't get any errors.

@TheFatherMind If you are still experiencing those problems and want to show them to me on your systems, please mail me at developer@maurice-meyer.de, PGP key with the fingerprint `C56B20A600EE30EE618FA6025D3C9B15D1BEE8BC` is available at the usual key servers.

**Comment by psi-4ward** [comment] 2017-07-20 14:01
Have you the php.ini settings:
`error_reporting = E_ALL`
`display_errors = On`
?

**Comment by psi-4ward** [comment] 2017-07-20 14:04
The error is totally clear:
`https://github.com/loewexy/pdnsmanager/blob/master/index.php` starts with `<!DOCTYPE html>` which leads to flush the output buffer. Starting with the first flush you are note able to modify the headers.

The Line in `https://github.com/loewexy/pdnsmanager/blob/master/lib/headers.php#L19` should be removed. If we need this header we have to adjust the apache / nginx config to deliver it.

**Comment by mauricemeyer** [comment] 2017-07-20 14:27
@psi-4ward Thanks for beating me to see what is obvious - while I was just wondering why I can't reproduce it. I just pushed 39dd3f86c68e26b7acfb6ccf929a37ede748550a to the master, where the headers are set before the HTML block starts.

While this should fix the issue, do you have any idea why I can't reproduce that? My `error_reporting` is set at `E_ALL` and `display_errors` is on, so I wonder why I don't get this error?

**Comment by psi-4ward** [comment] 2017-07-20 14:32
Hmm also check your php error log and apache error log

**Closed** 2017-07-20 14:34 UTC
Labels: bug

**Comment by mauricemeyer** [comment] 2017-07-20 14:39
@psi-4ward Did that, too. I'm using nginx + php-fpm with the nginx error log level set to `info`, doesn't give me anything, neither does the php-fpm error log (which I have set to my production values, that is workers logging to it, too).

This is really strange, I'll try to find out more about this.

**Comment by TheFatherMind** [comment] 2017-07-21 07:54
@mauricemeyer I have eMailed you login information to your own area so you can see this issue and play around.  My mail server is going through a DNS switch over and it got stuck in the queue.  I will eMail you from a different account in the mean time.
